name: hello-world-workflow

on:
  pull_request:
    branches:
      main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: print Hello World
        run: echo "Hello World" && sleep 30
      - name: print hello New Era Solution
        run: echo "Hello New Era Solution"
